### PR TITLE
Fix `kron` dimension bug, add simple test

### LINKED ISSUE #267: Bug in kron
The following gives (2,2) dimensional variable
```
z = ComplexVariable(2,2)
kron(z, [1 0;  0 1])
```

Switching the order of the arguments gives the correct (4,4) variable result. 
Unless I am misunderstanding  the meaning of dimensions, the result should be the same in both cases. In either way, both expressions should be multiply-capable with 4x4 matrices.

### PR DESCRIPTION
**Pull request by ericphanson**
Fixes #267, #209. The dimensions of `kron(A,B)` should be the same as the dimensions of `kron(B,A)`. I just copied the working method to fix the broken one, and put the `isreal` check on the value again. That check is mentioned in <https://github.com/JuliaOpt/Convex.jl/issues/204#issuecomment-315590295>, seems to be working around the strange behavior `Convex.jl` has with complex-typed but `isreal`-true values.

### CODE REVIEW

File: src/atoms/affine/kron.jl [hunk 1]
```diff
@@ -23,7 +23,11 @@ function kron(a::AbstractExpr, b::Value)
     for i in 1:size(a)[1]
         row = AbstractExpr[]
         for j in 1:size(a)[2]
-            push!(row, a[i, j] .* b)
+            if isreal(b)
+                push!(row, a[i, j] * real(b))
```
Comment (ararslan) [inline src/atoms/affine/kron.jl]: You should just be able to use this definition only and ditch the conditional, since `real` is a no-op for real inputs.

Comment (ericphanson) [reply src/atoms/affine/kron.jl]: If `b` is complex, we don't want to take the real part though. We just don't want the type to be complex if the entries of `b` are all real, otherwise it complains later. (Not my fix, just copying the workaround from the other method).

Comment (ararslan) [reply src/atoms/affine/kron.jl]: Oh sorry, I read the logic backwards for some reason.
